import { useRef } from 'react';
import { useAppSelector } from '@/store';
import { selectIsOSSleep } from '@/store/slices/os';
import useChangeEffect from './useChangeEffect';

// Generated by Claude 3.7 (Cline)
/**
 * Hook to manage extra logging functionality after device wakes up from sleep.
 * Logging is automatically enabled after sleep and then turned off after specified timeout.
 *
 * @param timeoutMs How long the logging should stay enabled before auto-disabling (default: 600000ms/10mins)
 * @returns A ref containing a boolean indicating if extra logging is enabled
 */
export default function useExtraLoggingAfterWakeUp(timeoutMs: number = 600000) {
  const isExtraLoggingEnabled = useRef(false);
  const isOSSleep = useAppSelector(selectIsOSSleep);

  useChangeEffect(() => {
    if (!isOSSleep) {
      // Device woke up from sleep, enable extra logging
      isExtraLoggingEnabled.current = true;

      // Disable logging after specified timeout to avoid filling logs
      const disableLoggingTimeout = setTimeout(() => {
        isExtraLoggingEnabled.current = false;
      }, timeoutMs);

      // Clear the timeout when the component unmounts or when isOSSleep changes
      return () => {
        clearTimeout(disableLoggingTimeout);
      };
    } else {
      // When device is sleeping, make sure logging is disabled
      isExtraLoggingEnabled.current = false;
    }
  }, [isOSSleep, timeoutMs]);

  return isExtraLoggingEnabled;
}
